### ISSUE TITLE
istio wasm log: did not find root id,503 response

### ISSUE THREAD

**Issue by jingslunt** [solo-io/proxy-runtime#72]
- Wasm Plugin
```
#https://raw.githubusercontent.com/solo-io/proxy-runtime/master/examples/addheader/assembly/index.ts
export * from "@solo-io/proxy-runtime/proxy"; // this exports the required functions for the proxy to interact with us.
import { RootContext, Context, registerRootContext, FilterHeadersStatusValues, stream_context } from "@solo-io/proxy-runtime";

class AddHeaderRoot extends RootContext {
  createContext(context_id: u32): Context {
    return new AddHeader(context_id, this);
  }
}

class AddHeader extends Context {
  constructor(context_id: u32, root_context: AddHeaderRoot) {
    super(context_id, root_context);
  }
  onResponseHeaders(a: u32, end_of_stream: bool): FilterHeadersStatusValues {
    const root_context = this.root_context;
    if (root_context.getConfiguration() == "") {
      stream_context.headers.response.add("hello", "world!");
    } else {
      stream_context.headers.response.add("hello", root_context.getConfiguration());
    }
    return FilterHeadersStatusValues.Continue;
  }
}

registerRootContext((context_id: u32) => { return new AddHeaderRoot(context_id); }, "add_header");
```
- istio-1.13.2

```
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: header-injection
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  url: oci://myharbor.com/wasm/add-header:v0.1
  imagePullPolicy: IfNotPresent
```
- ingressgateway log
```
2022-07-20T08:56:23.607988Z	warning	envoy wasm	wasm log: did not find root id 
2022-07-20T09:10:21.910168Z	warning	envoy wasm	wasm log: did not find root id 
2022-07-20T09:10:21.911999Z	warning	envoy wasm	wasm log: did not find root id 
2022-07-20T09:10:21.912758Z	warning	envoy wasm	wasm log: did not find root id 
2022-07-20T09:10:21.913249Z	warning	envoy wasm	wasm log: did not find root id 
```

- website http response:
200 to 503
```
HTTP/1.1 503 Service Unavailable
date: Wed, 20 Jul 2022 09:10:49 GMT
server: istio-envoy
transfer-encoding: chunked
```
